// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/kam/worker/github/sukee/node_modules/dumi/theme-default/slots/SocialIcon/index.js';
