// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { SiteContext } from '/Users/kam/worker/github/sukee/node_modules/dumi/dist/client/theme-api/context.js';
import { demos, components } from '../meta';
import { locales } from '../locales/config';

const entryExports = {
  
  
};

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider value={{
      pkg: {"name":"suko","description":"","version":"0.0.3","license":"MIT","repository":{"type":"git","url":"https://github.com/kampiu/sukee.git"},"author":"kampiu <1479376017@qq.com>"},
      historyType: "browser",
      entryExports,
      demos,
      components,
      locales,
      loading,
      setLoading,
      hostname: undefined,
      themeConfig: {"footer":"Copyright © 2013-2023 KK All Rights Reserved.","prefersColor":{"default":"light","switch":true},"nprogress":true,"lastUpdated":true,"name":"Sukee","nav":{"zh-CN":[{"title":"研发","link":"/introduce/development"},{"title":"组件","link":"/components/button"}],"en-US":[{"title":"Development","link":"/introduce/development_us"},{"title":"Components","link":"/components/button_us"}]},"actions":{"zh-CN":[{"type":"primary","text":"开始使用","link":"/guide/introduce"},{"text":"配置","link":"/config/base"}],"en-US":[{"type":"primary","text":"Start","link":"/guide/introduce-en"},{"text":"Config","link":"/config/base-en"}]},"features":{"zh-CN":[{"title":"内置全文搜索","details":"不需要接入任何三方服务，标题、正文、demo 等内容均可被搜索，支持多关键词搜索，且不会带来产物体积的增加。"},{"title":"更好的编译性能","details":"通过结合使用 Umi 4 MFSU、esbuild、SWC、持久缓存等方案，带来比 dumi 1.x 更快的编译速度。"},{"title":"开箱即用","details":"接入简单，安装即使用，全面融入 Ant Design 风格。"}],"en-US":[{"title":"Built-in Full-Text search","details":"There is no need to access any third-party services, and the contents such as title, text, demo, etc. can be searched, which supports multi-keyword search and will not increase the product volume."},{"title":"Better Compilation Performance","details":"By combining Umi 4 MFSU, esbuild, SWC, persistent cache and other schemes, it brings faster compilation speed than dumi1.x."},{"title":"Simple Use","details":"Simple access, installation and use, fully integrated into Ant Design 5.0 style."}]},"editLink":"https://github.com/kampiu/sukee/edit/master/{filename}"},
      _2_level_nav_available: true,
    }}>
      {outlet}
    </SiteContext.Provider>
  );
}
